In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/hope/.local/lib/python3.8/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [7]:
[1,2,3,5,7,3,11]

[1, 2, 3, 5, 7, 3, 11]

In [8]:
np.array([1,2,4,3,5,35])

array([ 1,  2,  4,  3,  5, 35])

In [9]:
a = np.array([3,4,6,2,4,6,3,6,3])

In [11]:
a[2]

6

In [12]:
a[2]= 9

In [13]:
a

array([3, 4, 9, 2, 4, 6, 3, 6, 3])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

multi-dementional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [3,5,4,],
    [4,2,6]
])

In [21]:
n[0][1]

2

In [22]:
n[0,1]

2

In [23]:
n[0,1] =20

In [24]:
n[0,1]

20

In [25]:
n[0]

array([ 1, 20,  3])

In [27]:
n[:,1]

array([20,  5,  2])

In [28]:
n[:,1] = [4,7,8]

In [29]:
n

array([[1, 4, 3],
       [3, 7, 4],
       [4, 8, 6]])

randomly generated arrays 

In [33]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [34]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [36]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a+1

array([1, 2, 3, 4, 5])

In [39]:
a*2

array([0, 2, 4, 6, 8])

In [40]:
10 + (a*2)

array([10, 12, 14, 16, 18])

In [41]:
10+ (a/2) ** 2

array([10.  , 10.25, 11.  , 12.25, 14.  ])

In [42]:
b = 10+ (a/2) ** 2

In [43]:
b

array([10.  , 10.25, 11.  , 12.25, 14.  ])

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a + b

array([10.  , 11.25, 13.  , 15.25, 18.  ])

comparison operations 

In [46]:
a >=2

array([False, False,  True,  True,  True])

In [47]:
a > b

array([False, False, False, False, False])

In [49]:
a[a<b]

array([0, 1, 2, 3, 4])

Summarizing operations

In [51]:
a

array([0, 1, 2, 3, 4])

In [50]:
a.min()

0

In [52]:
a.sum()

10

In [53]:
a.max()

4

In [54]:
a.std()

1.4142135623730951

In [55]:
n

array([[1, 4, 3],
       [3, 7, 4],
       [4, 8, 6]])

In [56]:
n.sum()

40